config/routes.rb
Rails.application.routes.draw do
  resources 'flights', only: [:show, :index], param: :name do
    get :purchase, on: :member
    post :transaction, on: :member
    get :list_transactions, on: :collection
  end
  root :to => "flights#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight
  attr_accessor :name, :cost

  def initialize(name:, cost:)
    @name = name
    @cost = (cost.to_f / 100)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :create_flights, only: :index
  before_action :format_flight_name, only: [:show, :purchase]
  before_action :format_amount, only: :purchase

  def index
  end

  def show
  end

  def purchase
  end

  def transaction
    amount = amount_to_charge(params[:name].split('-').last.to_i)
    third_party_purchase = params[:third_party] || false

    if third_party_purchase
      third_party_distribution(amount)
    else
      gateway_transaction(amount)
    end
  end

  def list_transactions
    url = "https://core.spreedly.com/v1/transactions.json?order=desc&count=100"

    @transactions = HttpClient.fetch_paginated_data(url)
  end

  private def gateway_transaction(amount)
    @env = Spreedly::Environment.new(ENV["SPREEDLY_ENV"], ENV["ACCESS_SECRET"])

    retain = params[:retain] || false

    transaction = @env.purchase_on_gateway(ENV["TEST_GATEWAY_TOKEN"], params[:payment_method_token], amount, retain_on_success: retain)

    if transaction.succeeded?
      flash[:notice] = "#{transaction.message} Payment received!"
    else
      flash[:alert] = "There was a problem with your transaction: #{transaction.message}"
    end

    redirect_to flight_url(name: params[:name].parameterize)
  end

  private def third_party_distribution(amount)
    url = "https://core.spreedly.com/v1/receivers/#{ENV["PMD_GATEWAY_TOKEN"]}/deliver.json"

    body = "{
        \"delivery\": {
          \"payment_method_token\": \"#{params[:payment_method_token]}\",
          \"url\": \"https://spreedly-echo.herokuapp.com\",
          \"headers\": \"Content-Type: application/json\",
          \"body\": \"{ \\\"flight\\\": \\\"#{params[:name]}\\\", \\\"amount\\\": \\\"#{amount}\\\", \\\"card_number\\\": \\\"{{credit_card_number}}\\\" }\"
        }
      }"

    response = HttpClient.make_request(:post, url, body)
    parsed_response = JSON.parse response.body

    if parsed_response['transaction']['response']['status'] == 200
      flash[:notice] = "Payment successfully delivered to third party seller!"
    else
      flash[:alert] = "There was a problem with your transaction."
    end
    
    redirect_to flight_url(name: params[:name].parameterize)
  end

  private def amount_to_charge(base)
    base * 10 + (base.divmod(10).last * 205)
  end

  private def cost_to_dollars(amount)
    amount.to_f / 100
  end

  private def format_flight_name
    @flight_name = params[:name].split("-").join(" ").humanize
  end

  private def format_amount
    @amount = cost_to_dollars(amount_to_charge(params[:name].split('-').last.to_i))
  end

  private def create_flights
    @flights = 10.times.map{ |n| Flight.new(name: "Flight 100#{n}", cost: amount_to_charge("100#{n}".to_i)) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flights/_listing.html.erb
<table class="ui celled table">
  <thead>
    <tr>
      <th>Flight Name</th>
      <th>Cost (USD)</th>
      <th>Buy Now!</th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |flight| %>
    <tr>
      <td><%= flight.name %></td>
      <td><%= number_to_currency(flight.cost) %></td>
      <td><%= link_to 'Purchase', purchase_flight_url(name: flight.name.parameterize) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/_payment_form.html.erb
<form id="payment-form" accept-charset="UTF-8" class="spf-form" method="POST"
  action="<%= action %>" onsubmit="submitPaymentForm(); return false;">

  <input type="hidden" name="payment_method_token" id="payment_method_token" value="" />
  <fieldset class="spf-fs-name">
    <h2>Name</h2>
    <div class="spf-field spf-field-fname">
      <label class="internal" for="spf-fname">First Name</label>
      <input type="text" class="spf-input-text" id="first_name">
    </div>
    <div class="spf-field spf-field-lname">
      <label class="internal" for="spf-lname">Last Name</label>
      <input type="text" class="spf-input-text" id="last_name">
    </div>
  </fieldset>

  <fieldset class="spf-fs-cc">
    <h2>Payment Details</h2>

    <div class="spf-field">
      <label class="spf-field-group spf-number">Credit Card Number</label>
      <div id="spreedly-number-test" class="spf-field-group spf-number spf-field-cc">
      </div>
      <label class="spf-field-group spf-verification_value">CVV</label>
      <div id="spreedly-cvv-test" class="spf-field-group spf-verification_value spf-field-cc">
      </div>
    </div>

    <div class="spf-field spf-field-exp">
      <label>Expiration Date</label>
      <div class="spf-field-group spf-month">
        <input type="text" class="spf-input-text spf-exp" id="month" size="3" maxlength="2" placeholder="MM">
      </div>
      <span class="spf-exp-divider">/</span>
      <div class="spf-field-group spf-year">
        <input type="text" class="spf-input-text spf-exp" id="year" size="5" maxlength="4" placeholder="YYYY">
      </div>
    </div>

    <div>
      <input type="checkbox" id="retain" name="retain" value="true">
      <label for="retain">Save payment info?</label>
    </div>
    <div>
      <input type="checkbox" id="third_party" name="third_party" value="true">
      <label for="third_party">Complete purchase via third-party?</label>
    </div>
  </fieldset>

  <fieldset class="spf-field-submit">
    <input type="submit" class="button" value="Submit Payment">
    <div id="message"></div>
    <div id="errors"></div>
  </fieldset>

  <script
    id="spreedly-iframe"
    data-environment-key="<%=ENV['SPREEDLY_ENV']%>"
    data-number-id="spreedly-number-test"
    data-cvv-id="spreedly-cvv-test">
  </script>
</form>

<script>
  Spreedly.init();
  Spreedly.on('paymentMethod', function(token, pmData) {
    var tokenField = document.getElementById("payment_method_token");
    tokenField.setAttribute("value", token);
    var masterForm = document.getElementById('payment-form');

    masterForm.submit();
  });
  Spreedly.on('errors', function(errors) {
    var messageEl = document.getElementById('errors');
    var errorBorder = "1px solid red";
    for(var i = 0; i < errors.length; i++) {
      var error = errors[i];
      if(error["attribute"]) {
        var masterFormElement = document.getElementById(error["attribute"]);
        if(masterFormElement) {
          masterFormElement.style.border = errorBorder
        } else {
          Spreedly.setStyle(error["attribute"], "border: " + errorBorder + ";");
        }
      }
      messageEl.innerHTML += error["message"] + "<br/>";
    }
  });
  Spreedly.on('ready', function(frame) {
    Spreedly.setFieldType('number', 'text');
    Spreedly.setFieldType('cvv', 'text');
    Spreedly.setNumberFormat('maskedFormat');
    Spreedly.setStyle('number','width: 67%; border-radius: 3px; border: 1px solid #ccc; padding: .65em .5em; font-size: 91%;');
    Spreedly.setStyle('cvv', 'width: 30%; border-radius: 3px; border: 1px solid #ccc; padding: .65em .5em; font-size: 91%;');
  });
  Spreedly.on('fieldEvent', function(name, event, activeElement, inputData) {
    if (event == 'input') {
      if (inputData["validCvv"]){
        Spreedly.setStyle('cvv', "background-color: #CDFFE6;")
      } else {
        Spreedly.setStyle('cvv', "background-color: #FFFFFF;")
      }
      if (inputData["validNumber"]){
        Spreedly.setStyle('number', "background-color: #CDFFE6;")
      } else {
        Spreedly.setStyle('number', "background-color: #FFFFFF;")
      }
    }
  });
  function submitPaymentForm() {
    var normalBorder = "1px solid #ccc";
    // These are the fields whose values we want to transfer *from* the
    // master form *to* the payment frame form. Add the following if
    // you're displaying the address:
    // ['address1', 'address2', 'city', 'state', 'zip', 'country']
    var paymentMethodFields = ['first_name', 'last_name', 'month', 'year']
    options = {};
    for(var i = 0; i < paymentMethodFields.length; i++) {
      var field = paymentMethodFields[i];
      // Reset existing styles (to clear previous errors)
      var fieldEl = document.getElementById(field);
      fieldEl.style.border = normalBorder;
      // add value to options
      options[field]  = fieldEl.value
    }
    // Reset frame styles
    Spreedly.setStyle('number', "border: " + normalBorder + ";");
    Spreedly.setStyle('cvv', "border: " + normalBorder + ";");
    // Reset previous messages
    document.getElementById('errors').innerHTML = "";
    document.getElementById('message').innerHTML = "";
    // Tokenize!
    Spreedly.tokenizeCreditCard(options);
  }
</script>

app/views/flights/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Flights✈️</h1>
  </div>

  <%= render 'flights/listing' %>
  <div>
    <%= link_to 'View Transactions', list_transactions_flights_url %>
  </div>
</div>

app/views/flights/list_transactions.html.erb
<div class="page-header">
  <h1>Recent Transactions</h1>
</div>
<p><%= link_to 'View all flights', flights_url %></p>
<table>
  <thead>
    <tr>
      <th>Type of transaction</th>
      <th>Token</th>
      <th>Created at</th>
      <th>Status Message</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction['transaction_type'] %></td>
        <td><%= transaction['token'] %></td>
        <td><%= transaction['created_at'] %></td>
        <td><%= transaction['message'] %></td>
        <td><%= %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flights/purchase.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Spreedly Sample iFrame Payment Page</title>
  <script src="https://core.spreedly.com/iframe/iframe-v1.min.js"></script>
</head>

<body>
  <h2><%= "You are about to purchase a seat on #{@flight_name}. Enter your payment information below to complete the transaction:" %></h2>
  <h4> <%= "Order details: 1 seat x #{number_to_currency(@amount)}" %> </h4>
  <%= render 'flights/payment_form', action: 'transaction' %>

  <h3>Sample Cards</h3>
  <table class="table span6">
      <tr>
        <th>Card Type</th>
        <th>Good Card</th>
        <th>Declined/Failed Card</th>
      </tr>
      <td>Visa</td>
      <td>4111111111111111</td>
      <td>4012888888881881</td>
      <tr>
        <td>MasterCard</td>
        <td>5555555555554444</td>
        <td>5105105105105100</td>
      </tr>
    </table>
</body>
</html>

app/views/flights/show.html.erb
<body>
<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% elsif flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="container">
  <div class="page-header">
    <h1><%= "#{@flight_name}" %></h1>
  </div>
  <% link_text = flash[:notice] ? 'Buy Another Seat' : 'Purchase'%>
  <p><%= link_to link_text, purchase_flight_url(name: params[:name]) %></p>
  <p><%= link_to 'View all flights', flights_url %></p>
</div>


</body>

app/views/flights/transaction.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Spreedly Sample iFrame Payment Page</title>
  <script src="https://core.spreedly.com/iframe/iframe-v1.min.js"></script>
</head>

<body>
  <h1>Test</h1>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreedlyAirlinesBrittany</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>